export const assets = [
    {
      name: "Cubicle",
      path: '/asset/Level_3_Cubicle.fbx',
      x: 300,
      y: -400, 
      z: -1800,
      xscale: 1, 
      yscale: 1,
      zscale: 1,
      b: 200,
      g: 100,
      r: 10
    },
    // {
    //   name: "Grey Squirrel NPC",
    //   path: '/asset/GreySquirrel_NPC.fbx',
    //   x: 250,
    //   y: -550, 
    //   z: -1800,
    //   xscale: 1, 
    //   yscale: 1,
    //   zscale: 1,
    //   b: 200,
    //   g: 100,
    //   r: 10
    // },
    {
      name: "Dividing Wall",
      path: '/asset/Level_3_Components/Level_3_DividingWall_01.fbx',
      x: 0,
      y: 0, 
      z: 0,
      xscale: 1, 
      yscale: 1,
      zscale: 1,
      b: 17 ,
      g: 55,
      r: 220
    },
    {
      name: "Floor",
      path: '/asset/Level_3_Components/Level_3_Floor.fbx',
      x: 0,
      y: 0, 
      z: 0,
      xscale: 1, 
      yscale: 1,
      zscale: 1,
      b: 220 ,
      g: 203,
      r: 100
    },
    {
      name: "Inner Wall 1",
      path: '/asset/Level_3_Components/Level_3_InnerWall_01.fbx',
      x: 0,
      y: 0, 
      z: 0,
      xscale: 1, 
      yscale: 1,
      zscale: 1,
      b: 50,
      g: 70,
      r: 230
    },
    {
      name: "Inner Wall 2",
      path: '/asset/Level_3_Components/Level_3_InnerWall_02.fbx',
      x: 0,
      y: 0, 
      z: 0,
      xscale: 1, 
      yscale: 1,
      zscale: 1,
      b: 177 ,
      g: 26,
      r: 189
    },
    {
      name: "Outer Wall",
      path: '/asset/Level_3_Components/Level_3_OuterWall.fbx',
      x: 0,
      y: 0, 
      z: 0,
      xscale: 1, 
      yscale: 1,
      zscale: 1,
      b: 255 ,
      g: 210,
      r: 18
    },
  ]